<?php
$redirects = [
    ['/404', '/', 301],
    ['/argumentative-essay/free-example', '/argumentative-essay-example', 301],
    ['/argumentative-essay/outline', '/argumentative-essay-outline', 301],
    ['/assignment-help-australia', '/assignment-help-service', 301],
    ['/assignment-help-online', '/assignment-help-service', 301],
    ['/assignment-help-service-essay', '/assignment-help-service', 301],
    ['/assignment-writing-help', '/assignment-help-service', 301],
    ['/book-authors', '/', 301],
    ['/cause-and-effect-essay-free-example/amp', '/blog/cause-and-effect-essay-free-example/amp', 301],
    ['/cause-effect-essay/outline', '/blog/cause-effect-essay-outline', 301],
    ['/cause-effect-essay/topics', '/blog/cause-effect-essay-topics', 301],
    ['/cause-effect-essay-outline/amp', '/blog/custom-book-report-template/amp', 301],
    ['/cause-effect-essay-topics/amp', '/blog/cause-effect-essay-topics/amp', 301],
    ['/case_study.html', '/case-study', 301],
    ['/college-essay/writing', '/college-essay-writing', 301],
    ['/college-students', '/', 301],
    ['/company-info', '/about-us', 301],
    ['/custom-book-report/template', '/blog/custom-book-report-template', 301],
    ['/custom-book-report-template/amp', '/blog/custom-book-report-template/amp', 301],
    ['/custom-essay/cause-and-effect-essay/free-example', '/blog/descriptive-essay-topics-and-ideas', 301],
    ['/control-panel', '/customers/login', 301],
    ['/custom-essay/descriptive-essay/topics-and-ideas', '/blog/descriptive-essay-topics-and-ideas', 301],
    ['/custom-essay/compare-and-contrast-essay', '/blog/compare-and-contrast-essay', 301],
    ['/custom-essay/persuasive-essay/topics-and-ideas', '/blog/persuasive-essay-topics-and-ideas', 301],
    ['/custom-essay/reflective-essay/free-example', '/blog/reflective-essay-free-example', 301],
    ['/custom-essay/expository-essay/free-example', '/blog/persuasive-essay-topics-and-ideas', 301],
    ['/custom-essay-2', '/custom-essay', 301],
    ['/custom-lab-report/format', '/blog/custom-lab-report-format', 301],
    ['/custom-lab-report-format/amp', '/blog/custom-lab-report-format/amp', 301],
    ['/custom-research-paper/format', '/blog/custom-research-paper-format', 301],
    ['/custom-research-paper/guideline', '/blog/custom-research-paper-guideline', 301],
    ['/custom-research-paper/how-to-write-a-research-paper', '/blog/how-to-write-a-research-paper', 301],
    ['/custom-research-paper/research-paper-outline', '/blog/research-paper-outline', 301],
    ['/custom-research-paper/research-paper-topics', '/blog/research-paper-topics', 301],
    ['/custom-research-paper/research-proposal', '/blog/research-proposal', 301],
    ['/custom-research-paper-format/amp', '/blog/custom-research-paper-format/amp', 301],
    ['/custom-research-paper-guideline/amp', '/blog/custom-research-paper-guideline/amp', 301],
    ['/descriptive-essay-topics-and-ideas/amp', '/blog/descriptive-essay-topics-and-ideas/amp', 301],
    ['/custom-essays', '/custom-essay', 301],
    ['/disclaimer', '/', 301],
    ['/discount-table', '/prices', 301],
    ['/doctoral-degrees', '/', 301],
    ['/do-my-essay', '/write-my-essay', 301],
    ['/downloadSampleFile/134', '/sample-papers', 301],
    ['/downloadSampleFile/135', '/sample-papers', 301],
    ['/downloadSampleFile/136', '/sample-papers', 301],
    ['/downloadSampleFile/137', '/sample-papers', 301],
    ['/downloadSampleFile/138', '/sample-papers', 301],
    ['/downloadSampleFile/139', '/sample-papers', 301],
    ['/downloadSampleFile/146', '/sample-papers', 301],
    ['/downloadSampleFile/55', '/sample-papers', 301],
    ['/downloadSampleFile/56', '/sample-papers', 301],
    ['/downloadSampleFile/60', '/sample-papers', 301],
    ['/downloadSampleFile/61', '/sample-papers', 301],
    ['/downloadSampleFile/63', '/sample-papers', 301],
    ['/downloadSampleFile/64', '/sample-papers', 301],
    ['/downloadSampleFile/65', '/sample-papers', 301],
    ['/downloadSampleFile/67', '/sample-papers', 301],
    ['/downloadSampleFile/68', '/sample-papers', 301],
    ['/essay-writing-assistance', '/', 301],
    ['/how-to-write-a-reflective-essay/amp', '/blog/how-to-write-a-reflective-essay/amp', 301],
    ['/how-to-write-a-research-paper/amp', '/blog/how-to-write-a-research-paper/amp', 301],
    ['/five-paragraph-essay/outline', '/five-paragraph-essay-outline', 301],
    ['/international-students', '/', 301],
    ['/law-degree', '/', 301],
    ['/my-assignment-help', '/assignment-help-service', 301],
    ['/login', '/customers/login', 301],
    ['/nursing-degrees', '/', 301],
    ['/order-custom-term-paper', '/term-paper-writing-service', 301],
    ['/our-history', '/about-us', 301],
    ['/our-offices', '/about-us', 301],
    ['/our-servers', '/about-us', 301],
    ['/our-services', '/editing-services', 301],
    ['/paid-assignment-writing', '/assignment-help-service', 301],
    ['/our-staff', '/about-us', 301],
    ['/paper-writing-service', '/', 301],
    ['/persuasive-essay-topics-and-ideas/amp', '/blog/persuasive-essay-topics-and-ideas/amp', 301],
    ['/pci-compliance', '/', 301],
    ['/privacy-policy', '/', 301],
    ['/reflective-essay/how-to-write', '/blog/how-to-write-a-reflective-essay', 301],
    ['/reflective-essay/how-to-write/amp', '/blog/how-to-write-a-reflective-essay/amp', 301],
    ['/reflective-essay-free-example/amp', '/blog/reflective-essay-free-example/amp', 301],
    ['/research-paper-outline/amp', '/blog/research-paper-outline/amp', 301],
    ['/research-paper-topics/amp', '/blog/research-paper-topics/amp', 301],
    ['/research-proposal/amp', '/blog/research-proposal/amp', 301],
    ['/professional-custom-writing', '/custom-writing', 301],
    ['/samples/dissertation-proposal-tourism-sample.pdf', '/sample-papers', 301],
    ['/satisfaction-guarantee', '/guarantees', 301],
    ['/term-paper-essay', '/term-paper-writing-service', 301],
    ['/term-paper-order', '/term-paper-writing-service', 301],
    ['/term-paper-writing-services', '/term-paper-writing-service', 301],
    ['/write-my-college-essay', '/write-my-essay', 301],
    ['/writing-paper-help', '/term-paper-writing-service', 301],
    ['/sitemap/amp', '/sitemap', 301],
    ['/blog/amp', '/blog', 301],
    ['/dissertation-help', '/dissertation-writing-service', 301],
    ['/custom-dissertation', '/dissertation-writing-service', 301],
    ['/term-paper-writing-service-2', '/term-paper-writing-service', 301],
    ['/settings', '/customers/login', 301],
    ['/custom-essay/argumentative-essay/free-example', '/argumentative-essay-example', 301],
    ['/essay-writing-common-mistakes', '/academic-writing', 301],
    ['/term-paper-writing-service-2', '/term-paper-writing-service', 301],
    ['/custom-essay/argumentative-essay/free-example', '/argumentative-essay-example', 301],

    ['/images/ozEssay/logo.svg?v=14', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=14', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/vb.svg?v=14', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=12','/wp-content/themes/ozessay/img/logo.svg',301],
    ['/images/ozEssay/pci.svg?v=9', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=13', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=11', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=13', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=14', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=11', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=14', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=1', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/norton.svg?v=11', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=13', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/vb.svg?v=1', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=11', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=12', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/vb.svg?v=13', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/cover.png?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v\u003d7', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=1', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/norton.svg?v=1', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=1', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/cover.png?v=9', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=9', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pay-pal.svg?v=9', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/pci.svg?v=2', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/vb.svg?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/vb.svg?v=11', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/norton.svg?v=3', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=2', '/wp-content/themes/ozessay/img/logo.svg', 301],
    ['/images/ozEssay/google-play-badge.svg?v=7', '/wp-content/themes/ozessay/img/logo.svg', 301],

    ['/blog/cause-and-effect-essay-free-exampleJan','/blog/cause-and-effect-essay-free-example', 301],
    ['/cause-and-effect-essay-free-exampleA','/blog/cause-and-effect-essay-free-example', 301],
    ['/descriptive_essay','/description-essay', 301],
    ['/descriptive-essay.html','/descriptive-essay', 301],
    ['/dissertation-proposal-tourismMay','/dissertation-proposal-tourism', 301],
    ['/expository-essay.html','/expository-essay', 301],
    ['/five-paragraph-essay.html','/five-paragraph-essay', 301],
    ['/how-to-communicate-with-your-writer.html','/how-to-communicate-with-your-writer', 301],
    ['/law_essay.html','/law-essay', 301],
    ['/reflective-essay.html','/reflective-essay', 301],
    ['/research-paper.html','/research-paper', 301],
    ['/resume-writing-essentials-how-to-prepare-write-and-market-yourself.html','/resume-writing-essentials-how-to-prepare-write-and-market-yourself', 301],
    ['/scholarship_essay.html','/scholarship-essay', 301],
    ['/prices/amp','/prices', 301],

    ['/expository_essay.html','/expository-essay',301],
    ['/who_are_we.html','/',301],
    ['/custom_research_paper.html','/custom-research-paper',301],
    ['/critical_essay.html','/critical-essay',301],
    ['/english_literature.html','/english-literature',301],
    ['/comparison_essay.html','/comparison-essay',301],
    ['/love_essay.html','/love-essay',301],

    ['/personal_essay.html','/blog/personal-essay',301],
    ['/personal_experience_essay.html','/blog/personal-essay',301],
    ['/blog/personal-experience-essay','/blog/personal-essay',301],

    ['/philosophy_essay.html','/philosophy-essay',301],
    ['/business_essay.html','/business-essay',301],
    ['/admission_application_essay.html','/admission-application-essay',301],
    ['/cause_and_effect_essay.html','/blog/cause-and-effect-essay-free-example',301],
    ['/critical-lens-essay-agree-or-disagree.html','/blog/critical-lens-essay-agree-or-disagree',301],
    ['/our_services.html','/editing-services',301]
];


for ($item = 0, $length = count($redirects); $item < $length; $item++) {
    if ($_SERVER['REQUEST_URI'] == $redirects[$item][0]) {
        wp_redirect(site_url() . $redirects[$item][1], $redirects[$item][2]);
        exit();
    }
}






